
exports.seed = function(knex, Promise) {
  
  return Promise.all([

    knex.insert([
      { andrew_id: 'mjs',  role: 'ca' },
      { andrew_id: 'koz',  role: 'ca' },
      { andrew_id: 'akalaba',  role: 'ca' },
      { andrew_id: 'ambikac',  role: 'ca' },
      { andrew_id: 'angelali',  role: 'ca' },
      { andrew_id: 'angogate',  role: 'ca' },
      { andrew_id: 'arajgarh',  role: 'ca' },
      { andrew_id: 'armanh',  role: 'ca' },
      { andrew_id: 'bsoderna',  role: 'ca' },
      { andrew_id: 'cs1',  role: 'ca' },
      { andrew_id: 'cwurman',  role: 'ca' },
      { andrew_id: 'cwz',  role: 'ca' },
      { andrew_id: 'edryer',  role: 'ca' },
      { andrew_id: 'hshalaby',  role: 'ca' },
      { andrew_id: 'jessieli',  role: 'ca' },
      { andrew_id: 'kbrackel',  role: 'ca' },
      { andrew_id: 'kevinzhe',  role: 'ca' },
      { andrew_id: 'kkleiven',  role: 'ca' },
      { andrew_id: 'lbp',  role: 'ca' },
      { andrew_id: 'mbgardne',  role: 'ca' },
      { andrew_id: 'mdwagner',  role: 'ca' },
      { andrew_id: 'mingnanx',  role: 'ca' },
      { andrew_id: 'moqings',  role: 'ca' },
      { andrew_id: 'nle',  role: 'ca' },
      { andrew_id: 'nnilakan',  role: 'ca' },
      { andrew_id: 'nraju',  role: 'ca' },
      { andrew_id: 'oweiss',  role: 'ca' },
      { andrew_id: 'pmishra1',  role: 'ca' },
      { andrew_id: 'poyuy',  role: 'ca' },
      { andrew_id: 'rkaufman',  role: 'ca' },
      { andrew_id: 'rkstokes',  role: 'ca' },
      { andrew_id: 'rlasko',  role: 'ca' },
      { andrew_id: 'rnvarma',  role: 'ca' },
      { andrew_id: 'ruohuil',  role: 'ca' },
      { andrew_id: 'sbhartiy',  role: 'ca' },
      { andrew_id: 'sbien',  role: 'ca' },
      { andrew_id: 'sboyle',  role: 'ca' },
      { andrew_id: 'shwang1',  role: 'ca' },
      { andrew_id: 'tiand',  role: 'ca' },
      { andrew_id: 'tstentz',  role: 'ca' },
      { andrew_id: 'vshanker',  role: 'ca' },
      { andrew_id: 'xinyiw',  role: 'ca' },
      { andrew_id: 'yeukyul',  role: 'ca' },
      { andrew_id: 'yongyiz',  role: 'ca' },
      { andrew_id: 'youngchk',  role: 'ca' },
      { andrew_id: 'youngjeh',  role: 'ca' },
      { andrew_id: 'yuzhes',  role: 'ca' }
    ]).into('valid_andrew_ids')
  ]);
};
