exports.seed = function(knex, Promise) {
  
  return Promise.all([

                knex.insert([
                        {andrew_id : "ambikac" , role : "ca" } ,  
                        {andrew_id : "angogate" , role : "ca" } ,  
                        {andrew_id : "armanh" , role : "ca" } ,  
                        {andrew_id : "azguo" , role : "ca" } ,  
                        {andrew_id : "bsoderna" , role : "ca" } ,  
                        {andrew_id : "cs1" , role : "ca" } ,  
                        {andrew_id : "cwurman" , role : "ca" } ,  
                        {andrew_id : "cwz" , role : "ca" } ,  
                        {andrew_id : "dyd" , role : "ca" } ,  
                        {andrew_id : "edryer" , role : "ca" } ,  
                        {andrew_id : "ethrashe" , role : "ca" } ,  
                        {andrew_id : "ewwong" , role : "ca" } ,  
                        {andrew_id : "eyluo" , role : "ca" } ,  
                        {andrew_id : "fmarsh" , role : "ca" } ,  
                        {andrew_id : "hshalab" , role : "ca" } ,  
                        {andrew_id : "hkillen" , role : "ca" } ,  
                        {andrew_id : "jessieli" , role : "ca" } ,  
                        {andrew_id : "jlenney" , role : "ca" } ,  
                        {andrew_id : "jmoavenz" , role : "ca" } ,  
                        {andrew_id : "jyzhao" , role : "ca" } ,  
                        {andrew_id : "kdchin" , role : "ca" } ,  
                        {andrew_id : "kevinzhe" , role : "ca" } ,  
                        {andrew_id : "kkleiven" , role : "ca" } ,  
                        {andrew_id : "kswells" , role : "ca" } ,  
                        {andrew_id : "lanhaow" , role : "ca" } ,  
                        {andrew_id : "lbp" , role : "ca" } ,  
                        {andrew_id : "mbgardne" , role : "ca" } ,  
                        {andrew_id : "mkasper" , role : "ca" } ,  
                        {andrew_id : "moqings" , role : "ca" } ,  
                        {andrew_id : "poyuy" , role : "ca" } ,  
                        {andrew_id : "raunaksg" , role : "ca" } ,  
                        {andrew_id : "rbhardw1" , role : "ca" } ,  
                        {andrew_id : "rishabhc" , role : "ca" } ,  
                        {andrew_id : "rjadvani" , role : "ca" } ,  
                        {andrew_id : "rkstokes" , role : "ca" } ,  
                        {andrew_id : "rnvarma" , role : "ca" } ,  
                        {andrew_id : "sbhartiy" , role : "ca" } ,  
                        {andrew_id : "sboyle" , role : "ca" } ,  
                        {andrew_id : "she2" , role : "ca" } ,  
                        {andrew_id : "tiand" , role : "ca" } ,  
                        {andrew_id : "tstentz" , role : "ca" } ,  
                        {andrew_id : "uar" , role : "ca" } ,  
                        {andrew_id : "xinhez" , role : "ca" } ,  
                        {andrew_id : "xinranl1" , role : "ca" } ,  
                        {andrew_id : "youngchk" , role : "ca" } ,  
                        {andrew_id : "yuzhes" , role : "ca" } ,  
                        {andrew_id : "zemingbh" , role : "ca" } ,  
                        {andrew_id : "koz", role : "ca" } , 
                        {andrew_id : "dga", role : "ca"}  
    ]).into('valid_andrew_ids')
  ]);
};
