exports.seed = function(knex, Promise) {
  
  return Promise.all([

                knex.insert([
                  
                        {andrew_id : "amarzoqi", role: "student" },
                        {andrew_id : "jiayub", role: "student" },
                        {andrew_id : "jiwonb", role: "student" },
                        {andrew_id : "cbanuelo", role: "student" },
                        {andrew_id : "dcascava", role: "student" },
                        {andrew_id : "junfanc", role: "student" },
                        {andrew_id : "eunicec1", role: "student" },
                        {andrew_id : "ric", role: "student" },
                        {andrew_id : "neild", role: "student" },
                        {andrew_id : "bding", role: "student" },
                        {andrew_id : "shenhanf", role: "student" },
                        {andrew_id : "yangg1", role: "student" },
                        {andrew_id : "cggonzal", role: "student" },
                        {andrew_id : "ashong", role: "student" },
                        {andrew_id : "shuangnh", role: "student" },
                        {andrew_id : "vivianh", role: "student" },
                        {andrew_id : "wenyuh", role: "student" },
                        {andrew_id : "cjhin", role: "student" },
                        {andrew_id : "yudij", role: "student" },
                        {andrew_id : "heecheok", role: "student" },
                        {andrew_id : "nikitaka", role: "student" },
                        {andrew_id : "malikk", role: "student" },
                        {andrew_id : "seongyek", role: "student" },
                        {andrew_id : "clknox", role: "student" },
                        {andrew_id : "ikrsek", role: "student" },
                        {andrew_id : "mansik", role: "student" },
                        {andrew_id : "gvlai", role: "student" },
                        {andrew_id : "clao", role: "student" },
                        {andrew_id : "yonghool", role: "student" },
                        {andrew_id : "yuqianl", role: "student" },
                        {andrew_id : "mllin", role: "student" },
                        {andrew_id : "mengliu", role: "student" },
                        {andrew_id : "surajn", role: "student" },
                        {andrew_id : "rnayyar", role: "student" },
                        {andrew_id : "yushano", role: "student" },
                        {andrew_id : "vpalepu", role: "student" },
                        {andrew_id : "apokhare", role: "student" },
                        {andrew_id : "acreddy", role: "student" },
                        {andrew_id : "tsengupt", role: "student" },
                        {andrew_id : "kseyidov", role: "student" },
                        {andrew_id : "tjshah", role: "student" },
                        {andrew_id : "avshanka", role: "student" },
                        {andrew_id : "nsrivas1", role: "student" },
                        {andrew_id : "bstone", role: "student" },
                        {andrew_id : "wsu1", role: "student" },
                        {andrew_id : "ntarn", role: "student" },
                        {andrew_id : "zteoh", role: "student" },
                        {andrew_id : "aou", role: "student" },
                        {andrew_id : "svideva", role: "student" },
                        {andrew_id : "svitoora", role: "student" },
                        {andrew_id : "xinciw", role: "student" },
                        {andrew_id : "andrewfw", role: "student" },
                        {andrew_id : "yuneily", role: "student" },
                        {andrew_id : "kehuiz", role: "student" },
                        {andrew_id : "shaojiez", role: "student" },
                        {andrew_id : "czhao2", role: "student" },
                        {andrew_id : "xinyuzha", role: "student" },
                        {andrew_id : "chenzhou", role: "student" },
                        {andrew_id : "yishunz", role: "student" }
       
    ]).into('valid_andrew_ids')
  ]);
};
